version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/railapi"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/railm"
    schedule:
      interval: "weekly"
    groups:
      flutter-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
